version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"
