codecov:
    require_ci_to_pass: true
    ci:
        - cd.screwdrvier.cd
coverage:
    precision: 2
    round: down
    range: "95...100"
    status:
        project:
            default:
                # basic
                enabled: yes
                target: auto
                threshold: 0%
                base: auto
                paths:
                    - "src"
                if_ci_failed: error
                informational: false
                only_pulls: true
comment:
    layout: "reach, diff, flags, files"
    behavior: new
    require_changes: false
    require_base: true
    require_head: false
