edit_uri: edit/master/docs/

extra:
    config_override: false
    doc_owner: Resilience Team
    doc_owner_shortid: ychaos-dev@verizonmedia.com
    version:
        provider: mike
    social:
        - icon: material/email
          link: mailto://ychaos-dev@verizonmedia.com
          name: Mail Resilience Team

extra_css: []

markdown_extensions:
    - admonition
    - codehilite
    - attr_list
    - markdown_include.include:
        base_path: docs
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
    - awesome-pages
    - mkdocstrings:
          watch:
              - src/ychaos

nav:
    - YChaos:
        - Home: index.md
        - Get Started: get_started.md
        - Changelog: releases.md
        - Contribution: contribution.md
        - Project Dependencies: dependencies.md
        - Code Of Conduct: code_of_conduct.md
        - FAQ: faq.md
    - ...

remote_branch: gh-pages
remote_name: origin
repo_name: yahoo/ychaos
repo_url: https://github.com/yahoo/ychaos
site_name: YChaos - The Resilience Toolkit
site_url: https://yahoo.github.io/ychaos
site_description: Python module ychaos
strict: false

theme:
    name: 'material'
    base_url: https://github.com/yahoo/ychaos
    language: 'en'
    features:
        - navigation.tabs
    palette:
      primary: 'white'
    icon:
        repo: fontawesome/brands/github

# Not Strictly Copyright :D
copyright: Maintained by Yahoo! Resilience Team

use_directory_urls: true
