version: 4
shared:
    settings:
        email:
            addresses:
                - ychaos-alerts@yahooinc.com
            statuses:
                - ABORTED
                - FAILURE
jobs:
    test_validation:
        template: python/validate_unittest@latest
        environment:
            TOX_ARGS: --parallel all
            TOX_ENVLIST: py38,py39,py310
        requires: [~pr]
        steps:
            - codecov: echo "Skip Codecov"
