version: 4
shared:
    environment:
        # Documentation tool to use, can be either sphinx which looks for documentation in doc/source
        # or mkdocs which looks for documentation in docs.
        # By default use [mkdocs](https://www.mkdocs.org/) tool to build documentation from the [docs](docs) directory.
        DOCUMENTATION_FORMATS: mkdocs

jobs:
    # Validation jobs
    dependency_validation:
        template: python/validate_dependencies
        requires: [~pr, ~commit]

    doc_validation:
         template: python/documentation
         environment:
             DOCUMENTATION_PUBLISH: False
         requires: [~pr]
         steps:
             - postinit: pip install -e .[doc_build]
             - prepublish_documentation: python3 screwdriver/autogen_docs.py

    lint_validation:
        template: python/validate_lint
        requires: [~pr, ~commit]

    package_validation:
        template: python/package_python
        environment:
            PACKAGE_PYTHON_PUBLISH: False
        requires: [~pr]

    security_validation:
        environment:
            SECURITY_BANDIT_CONFIG_ARGS: "-s B101"
        template: python/validate_security
        requires: [~pr, ~commit]

    # Style validation using `flake8`
    style_validation:
        template: python/validate_codestyle
        requires: [~pr, ~commit]
        steps:
            - validate_code: sd-cmd python/pypirun@latest flake8 flake8 src/ychaos

    # Code Format Validation using `black`
    code_format_validation:
        template: python/validate_codestyle
        requires: [~pr, ~commit]
        steps:
            - validate_code: sd-cmd python/pypirun@latest black black --check src/ tests/ develop/ setup.py

    test_validation:
        template: python/validate_unittest
        environment:
            TOX_ARGS: --parallel all
        requires: [~pr, ~commit]

    type_validation:
        template: python/validate_type
        requires: [~pr, ~commit]

    # Package auto-versioning, this must run before generating a package for publishing
    version:
        template: python/version
        requires: [dependency_validation, lint_validation, style_validation, type_validation, security_validation, test_validation, code_format_validation]

    # Python packaging
    python_package:
        template: python/package_python
        requires: [version]

    doc_publish:
        template: python/documentation
        requires: [python_package]
        steps:
            - postinit: pip install -e .[doc_build]
            - prepublish_documentation: python3 screwdriver/autogen_docs.py

