#  Copyright 2021, Verizon Media
#  Licensed under the terms of the ${MY_OSI} license. See the LICENSE file in the project root for terms

import json
from pathlib import Path
from unittest import TestCase

import jsondiff
from pkg_resources import resource_filename

from vzmi.ychaos.testplan import SystemState
from vzmi.ychaos.testplan.schema import TestPlan, TestPlanSchema
from vzmi.ychaos.testplan.verification import (
    VerificationConfig,
    PythonModuleVerification,
)


class TestSchemaDataClass(TestCase):
    def test_testplan_construction(self):
        testplan = TestPlan(
            verification=[
                VerificationConfig(
                    states=[SystemState.STEADY, SystemState.RECOVERED],
                    type="python_module",
                    config=dict(path="/directory/subdirectory/script.py"),
                ),
                VerificationConfig(
                    states=SystemState.CHAOS,
                    type="python_module",
                    config=dict(path="/directory/subdirectory/script.py"),
                ),
            ]
        )
        self.assertIsNotNone(testplan.id)
        self.assertEqual(len(testplan.verification), 2)
        self.assertEqual(
            len(testplan.filter_verification_by_state(SystemState.CHAOS)), 1
        )
        self.assertEqual(
            len(testplan.filter_verification_by_state(SystemState.RECOVERED)), 1
        )

        self.assertIsInstance(
            testplan.verification[0].get_parsed_config(), PythonModuleVerification
        )

    def test_testplan_schema_is_updated(self):
        # Validate the schema.json is up to date
        current_schema = TestPlanSchema.schema()

        PKG_RESOURCES = "vzmi.ychaos.testplan.resources"
        AUTOGEN_SCHEMA_FILE = str(resource_filename(PKG_RESOURCES, "schema.json"))

        schema_file = Path(AUTOGEN_SCHEMA_FILE)
        autogenerated_schema = json.loads(schema_file.read_text())

        difference = jsondiff.diff(current_schema, autogenerated_schema)

        if difference:
            print(difference)

        self.assertFalse(difference)
